In [1]:
#import numpy module with alias np
import numpy as np

# Define a numpy array passing a list with  1,2 and 3 as elements in it
arr = np.array([1, 2, 3])

# print output
print(arr)

# define a,b,c and d as instructed above
a = np.array(10)
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# print dimentions of a,b, c and d
print(a.ndim, b.ndim, c.ndim, d.ndim)

# print shape of each a,b ,c and d
print(a.shape, b.shape, c.shape, d.shape)

# print data type of c and d
print(c.dtype, d.dtype)

# print type of a and b variable
print(type(a), type(b))

# Lets check length of array b, using len() function
print(len(b))

# Define l1,l2,l3 and l4 as stated above.
l1 = [10, 20, 30]
l2 = [40, 50, 60]
l3 = np.array(l1)
l4 = np.array(l2)

#code here as instructed above
%timeit [l1[i] * l2[i] for i in range(len(l1))]

#code here as instructed above
%timeit l3 * l4

# Create a numpy array using arange with 1 and 11 as parameter in it
arr_range = np.arange(1, 11)

# Create an array using arange passing 1,11 and 2 as parameter in iter
arr_step = np.arange(1, 11, 2)

# create numpy array using eye function with 3 as passed parameter
eye_arr = np.eye(3)

# Using arange() to generate numpy array x with numbers between 1 to 16
x = np.arange(1, 17)

# Reshape x with 2 rows and 8 columns
x_reshaped_2d = x.reshape(2, 8)

# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:
x_reshaped_3d = x.reshape(2, 4, 2)

# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4
x_reshaped_2d_unknown = x.reshape(4, -1)

# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
y = x.reshape(2, 4, -1)

# print y
print(y)

# Flattening y
y_flattened = y.flatten()

# Create an array a with all even numbers between 1 to 17
a = np.arange(2, 18, 2)

# print a
print(a)

# Get third element in array a
print(a[2])

# Print 3rd, 5th, and 7th element in array a
print(a[[2, 4, 6]])

# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# print the 3rd element from the 3rd row of a
print(a[2, 2])

# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Print 3rd element from 2nd list which is 1st list in nested list passed.
print(b[0, 1, 2])

# Create 1D array
arr = np.arange(1, 10)

# Slice elements from 1st to 5th element from the following array:
print(arr[1:5])

# Slice elements from index 5 to the end of the array:
print(arr[5:])

# Slice elements from the beginning to index 5 (not included):
print(arr[:5])

# Print every other element from index 1 to index 7:
print(arr[1:7:2])

# Return every other element from the entire array arr:
print(arr[::2])

# Print array a
print(a)

# From the third element, slice elements from index 1 to index 5 (not included) from array 'a'
print(a[2, 1:5])

# In array 'a' print index 2 from all the elements :
print(a[:, 2])

# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:
print(a[:, 1:])

# x1=
x1 = np.array([1, 2, 3, 4, 5])

# assign x2 = x1
x2 = x1

#print x1 and x2
print(x1, x2)

# change 1st element of x2 as 10
x2[0] = 10

# Again print x1 and x2
print(x1, x2)

# Check memory share between x1 and x2
print(np.may_share_memory(x1, x2))

# Create a view of x1 and store it in x3.
x3 = x1.view()

# Again check memory share between x1 and x3
print(np.may_share_memory(x1, x3))

# Change 1st element of x3=100
x3[0] = 100

# print x1 and x3 to check if changes reflected in both
print(x1, x3)

# Now create an array x4 which is copy of x1
x4 = x1.copy()

# Change the last element of x4 as 900
x4[-1] = 900

# print both x1 and x4 to check if changes reflected in both
print(x1, x4)

# Check memory share between x1 and x4
print(np.may_share_memory(x1, x4))

# stack x1 and x4 along columns.
print(np.column_stack((x1, x4)))

# stack x1 and x4 along rows
print(np.vstack((x1, x4)))

# arr1 =
arr1 = np.array([1, 2, 3])

# arr2 =
arr2 = np.array([4, 5, 6])

# join arr1 and arr2 along rows using concatenate() function
print(np.concatenate((arr1, arr2), axis=0))

# join arr1 and arr2 along columns using concatenate() function
print(np.column_stack((arr1, arr2)))

# append arr2 to arr1
print(np.append(arr1, arr2))

# Inserts values into array x1 before index 4 with elements of x4
print(np.insert(x1, 4, x4))

# delete 2nd element from array x2
print(np.delete(x2, 2))


[1 2 3]
0 1 2 3
() (3,) (2, 3) (2, 2, 3)
int64 int64
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
3
1.7 µs ± 528 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.02 µs ± 171 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]
[ 2  4  6  8 10 12 14 16]
6
[ 6 10 14]
9
6
[2 3 4 5]
[6 7 8 9]
[1 2 3 4 5]
[2 4 6]
[1 3 5 7 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[8 9]
[3 6 9]
[[2 3]
 [5 6]
 [8 9]]
[1 2 3 4 5] [1 2 3 4 5]
[10  2  3  4  5] [10  2  3  4  5]
True
True
[100   2   3   4   5] [100   2   3   4   5]
[100   2   3   4   5] [100   2   3   4 900]
False
[[100 100]
 [  2   2]
 [  3   3]
 [  4   4]
 [  5 900]]
[[100   2   3   4   5]
 [100   2   3   4 900]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[100   2   3   4 100   2   3   4 900   5]
[100   2   4   5]
